version: '3'

services:
  backend:
    image: backend-2
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis

    ports: 
      - 8000:8000
    container_name: backend
    restart: unless-stopped

  frontend:
    image: frontend-2 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports: 
      - 5000:5000
    container_name: frontend

  redis:
    image: redis
    container_name: redis
